# Generated by Django 3.2.12 on 2022-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220317_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='e', max_length=254, verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='local_level',
            field=models.CharField(default='e', max_length=254, verbose_name='Local Level'),
            preserve_default=False,
        ),
    ]
