# Generated by Django 3.2.12 on 2022-04-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='Hobbies'),
        ),
    ]
