# Generated by Django 3.2.12 on 2022-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('music', 'Music')], max_length=254, null=True, verbose_name='Hobbies'),
        ),
    ]
