# Generated by Django 3.2.12 on 2022-05-22 06:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='local_level',
        ),
        migrations.AddField(
            model_name='user',
            name='lattitude',
            field=models.CharField(default=23, max_length=20, verbose_name='Lattitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default=43, max_length=20, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=80, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('music', 'Music')], max_length=15, null=True, verbose_name='hobbies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to=users.models.UPLOAD_IMAGE_PATH, verbose_name='profile photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='show'),
        ),
    ]
