# Generated by Django 3.2.12 on 2022-05-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220522_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_created_ip',
        ),
    ]
