# Generated by Django 3.2.12 on 2022-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_user_created_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(to='users.Hobby', verbose_name='hobbies'),
        ),
    ]
