# Generated by Django 3.2.12 on 2022-05-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
