# Generated by Django 3.2.12 on 2022-05-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
